### ISSUE TITLE
When db is empty, attempting to View All crashes the app

### ISSUE THREAD

**Issue by KeetonMartin** [KeetonMartin/swe-project-team-3#4]
If you boot up our app right now with an empty db folder (like we often do for the first time), the app launches, and you're able to add scholarships from the current home page.

However, unfortunately if you try to "View All" the scholarships, by going to the http://localhost:3000/all page, the app crashes due to an error:
`Emitted 'error' event on Function instance at:
    at /Users/keeton/Documents/courses/cs353/swe-project-team-3/node_modules/mongoose/lib/model.js:5000:15
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 'ERR_HTTP_HEADERS_SENT'`

This is likely fixable with some more robust checks for null / empty stuff somewhere... the question is where?

**Comment by qubist** [comment]
Can you post the whole stack trace?

**Comment by qubist** [comment]
Also do you mean completely empty `db/` folder? Doesn't the command to start up the database need to set some stuff up in there?

**Comment by KeetonMartin** [comment]
Good question Will. I'm pretty sure this issue is the same as the comment you made on my PR. Pretty sure that I don't mean completely empty `db/`, though I think this issue occurs anytime there are no scholarships in the db (including when they've all been deleted, as you mentioned). So yeah I think we're all talking about the same thing. Stack Trace: 

```
Deleted scholarship with id 624dcfe6884dec92cce97b35
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.header (/Users/keeton/Documents/courses/cs353/swe-project-team-3/scholarshipr/node_modules/express/lib/response.js:776:10)
    at ServerResponse.contentType (/Users/keeton/Documents/courses/cs353/swe-project-team-3/scholarshipr/node_modules/express/lib/response.js:604:15)
    at /Users/keeton/Documents/courses/cs353/swe-project-team-3/scholarshipr/index.js:129:9
    at /Users/keeton/Documents/courses/cs353/swe-project-team-3/scholarshipr/node_modules/mongoose/lib/model.js:5004:18
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
Emitted 'error' event on Function instance at:
    at /Users/keeton/Documents/courses/cs353/swe-project-team-3/scholarshipr/node_modules/mongoose/lib/model.js:5006:15
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by qubist** [comment]
> I'm pretty sure this issue is the same as the comment you made on my PR.

Yeah, seems like it!

> `at /Users/keeton/Documents/courses/cs353/swe-project-team-3/scholarshipr/index.js:129:9`

Chris's email about this issue might help us eventually solve it

**Comment by KeetonMartin** [comment]
I fixed it in my latest PR to main, feel free to check it out.
